# Q1

In [8]:
import cv2
import torch
import torch.nn.functional as F
import numpy as np

In [9]:
A = torch.ones(3,3) * 16
A = A.view(1, 1, 3, 3)
a = torch.tensor([1/2, 1/4, 1/2]).view(1, 1, 3, 1)
b = torch.tensor([1/2, 1/4, 1/2]).view(1, 1, 1, 3)
ab = a*b

In [10]:
print(A)
print(a)
print(b)
print(ab)

tensor([[[[16., 16., 16.],
          [16., 16., 16.],
          [16., 16., 16.]]]])
tensor([[[[0.5000],
          [0.2500],
          [0.5000]]]])
tensor([[[[0.5000, 0.2500, 0.5000]]]])
tensor([[[[0.2500, 0.1250, 0.2500],
          [0.1250, 0.0625, 0.1250],
          [0.2500, 0.1250, 0.2500]]]])


## 关于view为什么要这样




### 卷积核的view
```python
a = torch.tensor([1/2, 1/4, 1/2]).view(1, 1, 3, 1)
```

- (1, 1, 3, 1)代表什么？
    - 1 个输出通道
    - 1 个输入通道
    - 3x1 的卷积核

即使这个长相的卷积核，就必然只有 1 个输出通道，但是还是需要规定输出通道，更合理的原因，以后再补充

### A的view
A的view和a、b的view，虽然都是4维，但是含义存在不同。

在 PyTorch 中，F.conv2d 函数期望输入 A 是一个四维张量， **其形状为 (N, C, H, W)** ，分别代表：

- N：批次大小（Batch size），即一次前向传播中处理的数据样本数量。
- C：通道数（Channel），即输入数据的通道数量。
- H：高度（Height），即输入数据的高度。
- W：宽度（Width），即输入数据的宽度。

In [11]:
Aa = F.conv2d(A, a, padding=1)
Ab = F.conv2d(A, b, padding=1)

# 总的结果
Aa_b = F.conv2d(Aa, b)  # 先用a向量进行卷积，再用b
Ab_a = F.conv2d(Ab, a)  # 先用b向量进行卷积，再用a
A_ab = F.conv2d(A, ab, padding=1)  # 

Aa_b==A_ab
A_ab==Ab_a

tensor([[[[True, True, True],
          [True, True, True],
          [True, True, True]]]])

In [12]:
Aa

tensor([[[[ 0., 12., 12., 12.,  0.],
          [ 0., 20., 20., 20.,  0.],
          [ 0., 12., 12., 12.,  0.]]]])

In [23]:
a = torch.tensor([0, 0, 1.25]).view(1, 1, 3, 1)
Aa = F.conv2d(A, a, padding=1)
Aa

tensor([[[[ 0., 20., 20., 20.,  0.],
          [ 0., 20., 20., 20.,  0.],
          [ 0.,  0.,  0.,  0.,  0.]]]])

In [13]:
Aa_b

tensor([[[[ 9., 15.,  9.],
          [15., 25., 15.],
          [ 9., 15.,  9.]]]])

## 算法复杂度